name: Publish Website

on:
  push:
    branches:
      - main

env:
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
  AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}

jobs:
  publish-test:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Purge existing content
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az storage blob delete-batch --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} --account-key ${{ env.AZURE_STORAGE_ACCESS_KEY }} --source '${{ env.CONTAINER_NAME }}/test' --pattern "*"

    - name: Publish to test site
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} --account-key ${{ env.AZURE_STORAGE_ACCESS_KEY }} --destination '${{ env.CONTAINER_NAME }}/test' --source . --pattern "*"

  publish-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: publish-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Purge existing content
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az storage blob delete-batch --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} --account-key ${{ secrets.AZURE_STORAGE_ACCESS_KEY }} --source ${{ env.CONTAINER_NAME }}/prod --pattern "*"

    - name: Publish to prod site
      if: github.event_name == 'workflow_dispatch' || github.event_name == 'approval'
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} --account-key ${{ secrets.AZURE_STORAGE_ACCESS_KEY }} --destination ${{ env.CONTAINER_NAME }}/prod --source . --pattern "*"